-- Expand the Booking aggregate for the A4b state machine.
--
-- Notes:
-- * The bookings table is empty in dev/test (A4a only wrote the skeleton row
--   for the consume round-trip and rolled it back in tests). Adding NOT NULL
--   columns without DEFAULTs is therefore safe here. If/when this lands in
--   any environment with existing rows, switch to a multi-step backfill.
-- * The "ALTER TYPE ... ADD VALUE" calls run outside a transaction in
--   PostgreSQL >= 12 (we are on 16). The boilerplate comment about PG 11
--   is generated by `prisma migrate diff` and does not apply to us.

ALTER TYPE "BookingStatus" ADD VALUE 'CONFIRMED';
ALTER TYPE "BookingStatus" ADD VALUE 'DRIVER_ASSIGNED';
ALTER TYPE "BookingStatus" ADD VALUE 'IN_PROGRESS';
ALTER TYPE "BookingStatus" ADD VALUE 'COMPLETED';
ALTER TYPE "BookingStatus" ADD VALUE 'CANCELLED_BY_CUSTOMER';
ALTER TYPE "BookingStatus" ADD VALUE 'CANCELLED_BY_DRIVER';
ALTER TYPE "BookingStatus" ADD VALUE 'EXPIRED';
ALTER TYPE "BookingStatus" ADD VALUE 'DISPUTED';

-- AlterTable
ALTER TABLE "bookings" ADD COLUMN     "cancellation_reason" TEXT,
ADD COLUMN     "cancelled_at" TIMESTAMP(3),
ADD COLUMN     "cancelled_by_user_id" UUID,
ADD COLUMN     "category_id" UUID NOT NULL,
ADD COLUMN     "completed_at" TIMESTAMP(3),
ADD COLUMN     "confirmed_at" TIMESTAMP(3),
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'TRY',
ADD COLUMN     "deleted_at" TIMESTAMP(3),
ADD COLUMN     "driver_assigned_at" TIMESTAMP(3),
ADD COLUMN     "driver_id" UUID,
ADD COLUMN     "dropoff_address" TEXT NOT NULL,
ADD COLUMN     "dropoff_lat" DECIMAL(10,7) NOT NULL,
ADD COLUMN     "dropoff_lng" DECIMAL(10,7) NOT NULL,
ADD COLUMN     "event_end_at" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "event_start_at" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "expired_at" TIMESTAMP(3),
ADD COLUMN     "pickup_address" TEXT NOT NULL,
ADD COLUMN     "pickup_lat" DECIMAL(10,7) NOT NULL,
ADD COLUMN     "pickup_lng" DECIMAL(10,7) NOT NULL,
ADD COLUMN     "started_at" TIMESTAMP(3),
ADD COLUMN     "total_amount" DECIMAL(10,2) NOT NULL,
ADD COLUMN     "vehicle_id" UUID,
ADD COLUMN     "vehicle_type_id" UUID NOT NULL;

-- CreateIndex
CREATE INDEX "bookings_status_event_start_at_idx" ON "bookings"("status", "event_start_at");

-- CreateIndex
CREATE INDEX "bookings_driver_id_status_idx" ON "bookings"("driver_id", "status");

-- CreateIndex
CREATE INDEX "bookings_event_start_at_idx" ON "bookings"("event_start_at");

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_cancelled_by_user_id_fkey" FOREIGN KEY ("cancelled_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "driver_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_vehicle_type_id_fkey" FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "service_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
